<a href="https://colab.research.google.com/github/YixiaoHong/Finencial-Engineering-P1/blob/master/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Finencial Engineering Computational Project

## Yixiao Hong - 1001311145
## Hongzheng Xu - 1001772904

In [1]:
#Import libraries needed for the project:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


## 1.0 Data Importing and Cleaning

In [2]:
stocksNameList = ['F','CAT','DIS','MCD','KO','PEP','WMT','C','WFC','JPM','AAPL','IBM','PFE','JNJ','XOM','MRO','ED','T','VZ','NEM']
print('Stock names:',stocksNameList)
print(len(stocksNameList))

Stock names: ['F', 'CAT', 'DIS', 'MCD', 'KO', 'PEP', 'WMT', 'C', 'WFC', 'JPM', 'AAPL', 'IBM', 'PFE', 'JNJ', 'XOM', 'MRO', 'ED', 'T', 'VZ', 'NEM']
20


In [3]:
df =pd.read_csv('https://raw.githubusercontent.com/YixiaoHong/Finencial-Engineering-P1/master/data/AAPL.csv')
df_stock = df[['Date']]

for i in stocksNameList:
  path = 'https://raw.githubusercontent.com/YixiaoHong/Finencial-Engineering-P1/master/data/' + i +'.csv'
  df =pd.read_csv(path)
  df_stock[i] = df[['Adj Close']]
print (df_stock.shape)

(48, 21)


In [4]:
#for now we only keep the data from Dec-30-2004 to Sep-30-2008 (Oct-1-2008)
df_stock = df_stock.loc[:45,:]
df_stock['Date'] = df_stock['Date'].astype('datetime64[ns]') 
print (df_stock.head())

        Date         F        CAT  ...          T         VZ        NEM
0 2005-01-01  8.607593  28.674561  ...  10.387199  14.897937  33.243374
1 2005-02-01  8.330702  30.859501  ...  10.653401  15.219813  35.969017
2 2005-03-01  7.461411  29.687452  ...  10.489573  15.020938  33.770912
3 2005-04-01  5.999423  28.586847  ...  10.538280  15.147880  30.417458
4 2005-05-01  6.642731  30.841572  ...  10.492134  15.161038  29.832663

[5 rows x 21 columns]


In [5]:
#Get the monthly return samples
df_monthly_r = df_stock.copy()
for row in range(45):
  for col in range(1,21):
    r = (df_monthly_r.iloc[row+1,col]-df_monthly_r.iloc[row,col])/df_monthly_r.iloc[row,col]
    df_monthly_r.iat[row,col] = r

#delete the last row+
df_monthly_r.drop(df_monthly_r.tail(1).index,inplace=True)

df_monthly_r_data = df_monthly_r.drop(columns=['Date'])

display(df_monthly_r_data)

F       CAT       DIS  ...         T        VZ       NEM
0  -0.032168  0.076198 -0.024101  ...  0.025628  0.021605  0.081991
1  -0.104348 -0.037980  0.028275  ... -0.015378 -0.013067 -0.061111
2  -0.195940 -0.037073 -0.081100  ...  0.004643  0.008451 -0.099300
3   0.107228  0.078873  0.039394  ... -0.004379  0.000869 -0.019226
4   0.026053  0.012751 -0.082361  ...  0.015825 -0.023459  0.050946
5   0.048828  0.131256  0.018268  ...  0.029474 -0.009262 -0.037919
6  -0.063099  0.034149 -0.017550  ... -0.001775 -0.031921  0.054061
7  -0.011033  0.058749 -0.042080  ... -0.004568 -0.000612  0.191764
8  -0.156186 -0.104851  0.009946  ... -0.005007 -0.036097 -0.094672
9  -0.010683  0.103665  0.022979  ...  0.058695  0.029302  0.082629
10 -0.050430 -0.000173 -0.038508  ... -0.016860 -0.058161  0.160283
11  0.111399  0.175351  0.067283  ...  0.059616  0.051129  0.157303
12 -0.060193  0.080579  0.105887  ...  0.077559  0.079808 -0.143690
13 -0.001255 -0.017378 -0.003573  ... -0.019935  0.010682 -0.019463
14 -0.126885  0.054727  0.002510  ... -0.030696 -0.030240  0.126802
15  0.044726 -0.033778  0.090844  ...  0.006632 -0.042582 -0.106409
16 -0.032123  0.020974 -0.016393  ...  0.070223  0.073053  0.014957
17 -0.037518 -0.048470 -0.010333  ...  0.075296  0.009854 -0.030274
18  0.264046 -0.059702 -0.001347  ...  0.050532  0.054478  0.000391
19 -0.033453 -0.008289  0.042496  ...  0.045937  0.055429 -0.165854
20  0.023486 -0.077356  0.017793  ...  0.051904 -0.003501  0.061020
21 -0.018116  0.026199  0.050540  ...  0.000238 -0.007927  0.036227
22 -0.076261 -0.011284  0.036914  ...  0.054261  0.065827 -0.037519
23  0.082556  0.044676  0.035685  ...  0.052587  0.034372  0.001010
24 -0.027061  0.010680 -0.026159  ... -0.011726 -0.017675  0.000000
25 -0.002528  0.040354  0.005255  ...  0.071468  0.013903 -0.068958
26  0.019011  0.083396  0.015974  ... -0.018007  0.006857 -0.004598
27  0.037314  0.086771  0.013151  ...  0.077415  0.153285 -0.024461
28  0.129496 -0.003563 -0.023499  ...  0.003870 -0.054216 -0.039823
29 -0.096603  0.006386 -0.033392  ... -0.056385  0.035220  0.071454
30 -0.082256 -0.034432  0.018182  ...  0.027032 -0.007102  0.012216
31  0.087068  0.035107  0.023512  ...  0.061199  0.057307  0.058448
32  0.044759 -0.048706  0.006979  ... -0.012290  0.040425  0.140638
33 -0.153326 -0.031803 -0.042738  ... -0.077870 -0.052470 -0.023772
34 -0.103862  0.009179 -0.026244  ...  0.087673  0.011109 -0.017308
35 -0.013373 -0.021637 -0.065603  ... -0.073869 -0.111239  0.113239
36 -0.016566  0.024615  0.086126  ... -0.086267 -0.054595 -0.056774
37 -0.124043  0.082400 -0.031780  ...  0.099626  0.003580 -0.114716
38  0.444056  0.045855  0.033461  ...  0.010705  0.060603 -0.022114
39 -0.176755  0.013901  0.036078  ...  0.041420  0.012147  0.075096
40 -0.292647 -0.106728 -0.071428  ... -0.155639 -0.079802  0.097412
41 -0.002079 -0.058250 -0.027244  ... -0.085485 -0.038418 -0.078561
42 -0.070833  0.023500  0.065898  ...  0.051165  0.045254 -0.059633
43  0.165919 -0.157359 -0.051314  ... -0.127227 -0.086276 -0.140577
44 -0.578846 -0.359061 -0.155751  ... -0.041189 -0.075413 -0.318847

[45 rows x 20 columns]

In [6]:
#compute the sample mean for each stock (n=45)
sample_means = df_monthly_r_data.mean(axis = 0) 
display(sample_means)

F      -0.024767
CAT     0.002276
DIS     0.000021
MCD     0.016395
KO      0.006798
PEP     0.004174
WMT     0.003744
C      -0.023051
WFC     0.009118
JPM     0.007839
AAPL    0.031563
IBM     0.003081
PFE    -0.001950
JNJ     0.001406
XOM     0.011410
MRO     0.019815
ED      0.004677
T       0.008135
VZ      0.002234
NEM    -0.004393
dtype: float64

In [7]:
#sample variance for each stock
sample_std = df_monthly_r_data.std(axis = 0, ddof=1)
sample_var = sample_std**2
display(sample_var) 

F       0.021957
CAT     0.007196
DIS     0.002523
MCD     0.002818
KO      0.002031
PEP     0.002249
WMT     0.002129
C       0.008495
WFC     0.005702
JPM     0.005632
AAPL    0.016221
IBM     0.004144
PFE     0.002892
JNJ     0.001277
XOM     0.003762
MRO     0.011952
ED      0.001452
T       0.003348
VZ      0.002610
NEM     0.009671
dtype: float64

In [8]:
#compute sample covariances
stock_cov = np.cov(df_monthly_r_data.T)

display(stock_cov)

array([[ 2.19571849e-02,  5.98011908e-03,  3.26562149e-03,
         3.19291322e-03,  2.75749820e-03,  2.27921991e-03,
         2.74777161e-03,  8.78443030e-03,  3.15327152e-03,
         4.94759276e-03,  2.88076734e-03,  4.67733099e-03,
         1.58508508e-03,  1.85570584e-03,  2.94001642e-03,
         4.39637320e-03,  1.00835062e-03,  1.64008719e-03,
         2.44857244e-03,  3.68185030e-03],
       [ 5.98011908e-03,  7.19551082e-03,  2.32417253e-03,
         1.83091738e-03,  1.78325199e-03,  1.65086433e-03,
         3.79189396e-04,  2.92681749e-03, -2.40942317e-04,
         6.39006455e-04,  4.75301202e-03,  2.54405801e-03,
         1.19077051e-03,  6.81283528e-04,  2.19196643e-03,
         5.22967383e-03, -6.42331534e-05,  2.22480224e-03,
         2.10347191e-03,  3.90776114e-03],
       [ 3.26562149e-03,  2.32417253e-03,  2.52276056e-03,
         1.11835215e-03,  1.10032479e-03,  1.05358013e-03,
         4.31567342e-04,  1.61271023e-03, -2.69939317e-04,
         1.74696983e-04,  1.5

In [9]:
stock_cov.shape

(20, 20)

In [0]:
#Compute estimated market protfolio

#Searched shares outstandingg of the 20 stocks as of Sepetember 2008:

shares_outstanding = {
    'F':2.279,
    'CAT':0.625,
    'DIS':1.948,
    'MCD':1.136,
    'KO':4.658,
    'PEP':1.593,
    'WMT':3.958,
    'C':0.583,
    'WFC':3.331,
    'JPM':3.445,
    'AAPL':6.315,
    'IBM':1.384,
    'PFE':6.736,
    'JNJ':2.831,
    'XOM':5.178,
    'MRO':0.711,
    'ED':0.274,
    'T':5.893,
    'VZ':2.845,
    'NEM':0.455
}

In [11]:
pd_shares_outstanding = pd.Series(shares_outstanding)
display(pd_shares_outstanding)

F       2.279
CAT     0.625
DIS     1.948
MCD     1.136
KO      4.658
PEP     1.593
WMT     3.958
C       0.583
WFC     3.331
JPM     3.445
AAPL    6.315
IBM     1.384
PFE     6.736
JNJ     2.831
XOM     5.178
MRO     0.711
ED      0.274
T       5.893
VZ      2.845
NEM     0.455
dtype: float64

In [12]:
stock_mean = df_stock.mean(axis = 0) 
display(stock_mean)

F         5.494143
CAT      44.086372
DIS      25.060961
MCD      29.091344
KO       13.739939
PEP      42.783149
WMT      35.840620
C       374.071198
WFC      21.676198
JPM      30.142755
AAPL     12.169689
IBM      65.749778
PFE      13.908612
JNJ      42.787426
XOM      47.892939
MRO      17.131268
ED       25.003821
T        15.442895
VZ       17.219285
NEM      37.200083
dtype: float64

In [13]:
market_capital = stock_mean*pd_shares_outstanding
market_capital

F        12.521151
CAT      27.553983
DIS      48.818751
MCD      33.047767
KO       64.000634
PEP      68.153557
WMT     141.857173
C       218.083509
WFC      72.203415
JPM     103.841790
AAPL     76.851588
IBM      90.997693
PFE      93.688413
JNJ     121.131203
XOM     247.989639
MRO      12.180331
ED        6.851047
T        91.004978
VZ       48.988865
NEM      16.926038
dtype: float64

In [14]:
total_mrkt = market_capital.sum()
x_p_mrkt = market_capital/total_mrkt
x_p_mrkt

F       0.007842
CAT     0.017257
DIS     0.030575
MCD     0.020698
KO      0.040083
PEP     0.042684
WMT     0.088844
C       0.136585
WFC     0.045221
JPM     0.065036
AAPL    0.048132
IBM     0.056991
PFE     0.058677
JNJ     0.075864
XOM     0.155315
MRO     0.007628
ED      0.004291
T       0.056996
VZ      0.030681
NEM     0.010601
dtype: float64

In [15]:
#calculate market expected return rate

r_exp_mrkt = np.dot(sample_means,x_p_mrkt)
r_exp_mrkt

0.0028579824289776505

In [16]:
#calculate market expected variance
x_p_mrkt = np.array(x_p_mrkt).reshape(20,1)
r_exp_var = np.dot(np.dot(x_p_mrkt.T,stock_cov),x_p_mrkt)[0][0]
r_exp_var

0.0014346283890455417

risk free rate
https://www.macrotrends.net/2016/10-year-treasury-bond-rate-yield-chart


In [17]:
rf_month = 0.0363/12
rf_month

0.003025

In [18]:
#Risk aversion coefficient lambda

λ = (r_exp_mrkt-rf_month)/r_exp_var
λ

-0.1164186992935963

Build the market portfolio (Assume the 20 stocks are the all market size)

In [19]:
!pip install qpsolvers

https://pypi.org/project/qpsolvers/


https://scaron.info/blog/quadratic-programming-in-python.html


In [38]:
f = np.zeros(20)
print(f.shape)
print(f)

(20,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
A = -1*np.array(sample_means)
print(A.shape)
print(A)

(20,)
[ 2.47672181e-02 -2.27597375e-03 -2.06740796e-05 -1.63954823e-02
 -6.79777556e-03 -4.17430824e-03 -3.74375358e-03  2.30509605e-02
 -9.11769936e-03 -7.83930154e-03 -3.15632374e-02 -3.08112933e-03
  1.94988622e-03 -1.40590012e-03 -1.14095467e-02 -1.98145068e-02
 -4.67715734e-03 -8.13488780e-03 -2.23365579e-03  4.39310731e-03]


In [40]:
b = array([-2*λ])
print(b.shape)
print(b)

(1,)
[0.2328374]


In [41]:
Aeq = np.ones(20)
print(Aeq.shape)
print(Aeq)

(20,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [42]:
beq = array([1.])
print(beq.shape)
print(beq)

(1,)
[1.]


In [44]:
from numpy import array, dot
from qpsolvers import solve_qp
x_p_MVO = solve_qp(stock_cov, f, A, b, Aeq, beq, solver='quadprog')
print ("QP solution:", x_p_MVO)

QP solution: [-0.07963787 -0.06419846  0.14817449 -0.02200612  0.0083302   0.10612217
  0.29555703 -0.04815058  0.10866972 -0.07032062 -0.04284721  0.03037792
  0.07430081 -0.01230012  0.18355506 -0.03571744  0.19738042  0.03941905
  0.09099583  0.09229571]


In [45]:
r_exp_p1_MVO = np.dot(sample_means,x_p_MVO)
r_exp_p1_MVO

0.005631358274915938