<a href="https://colab.research.google.com/github/YixiaoHong/Finencial-Engineering-P1/blob/master/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Finencial Engineering Computational Project

## Yixiao Hong - 1001311145
## Hongzheng Xu - 1001772904

In [0]:
#Import libraries needed for the project:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

!pip install qpsolvers

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
import scipy as sp

# Problem a)

## 1.0 Data Importing and Cleaning

In [0]:
stocksNameList = ['F','CAT','DIS','MCD','KO','PEP','WMT','C','WFC','JPM','AAPL','IBM','PFE','JNJ','XOM','MRO','ED','T','VZ','NEM']
print('Stock names:',stocksNameList)
print(len(stocksNameList))

Stock names: ['F', 'CAT', 'DIS', 'MCD', 'KO', 'PEP', 'WMT', 'C', 'WFC', 'JPM', 'AAPL', 'IBM', 'PFE', 'JNJ', 'XOM', 'MRO', 'ED', 'T', 'VZ', 'NEM']
20


In [0]:
df =pd.read_csv('https://raw.githubusercontent.com/YixiaoHong/Finencial-Engineering-P1/master/data/AAPL.csv')
df_stock_price_full = df[['Date']]

for i in stocksNameList:
  path = 'https://raw.githubusercontent.com/YixiaoHong/Finencial-Engineering-P1/master/data/' + i +'.csv'
  df =pd.read_csv(path)
  df_stock_price_full[i] = df[['Adj Close']]
print (df_stock_price_full.shape)

(48, 21)


In [0]:
df_stock_price_full['Date'] = df_stock_price_full['Date'].astype('datetime64[ns]') 
display(df_stock_price_full)

Date         F        CAT  ...          T         VZ        NEM
0  2005-01-01  8.607593  28.674561  ...  10.387199  14.897937  33.243374
1  2005-02-01  8.330702  30.859501  ...  10.653401  15.219813  35.969017
2  2005-03-01  7.461411  29.687452  ...  10.489573  15.020938  33.770912
3  2005-04-01  5.999423  28.586847  ...  10.538280  15.147880  30.417458
4  2005-05-01  6.642731  30.841572  ...  10.492134  15.161038  29.832663
5  2005-06-01  6.815792  31.234846  ...  10.658173  14.805373  31.352509
6  2005-07-01  7.148591  35.334606  ...  10.972307  14.668242  30.163643
7  2005-08-01  6.697522  36.541264  ...  10.952836  14.200024  31.794313
8  2005-09-01  6.623626  38.688038  ...  10.902798  14.191338  37.891315
9  2005-10-01  5.589106  34.631557  ...  10.848213  13.679079  34.304070
10 2005-11-01  5.529397  38.221649  ...  11.484946  14.079909  37.138592
11 2005-12-01  5.250547  38.215038  ...  11.291306  13.261004  43.091263
12 2006-01-01  5.835453  44.916080  ...  11.964446  13.939023  49.869667
13 2006-02-01  5.484200  48.535389  ...  12.892397  15.051475  42.703918
14 2006-03-01  5.477318  47.691948  ...  12.635390  15.212262  41.872761
15 2006-04-01  4.782331  50.301987  ...  12.247540  14.752237  47.182331
16 2006-05-01  4.996226  48.602898  ...  12.328770  14.124054  42.161705
17 2006-06-01  4.835732  49.622288  ...  13.194529  15.155863  42.792336
18 2006-07-01  4.654305  47.217113  ...  14.188019  15.305209  41.496845
19 2006-08-01  5.883255  44.398163  ...  14.904973  16.139000  41.513054
20 2006-09-01  5.686442  44.030140  ...  15.589662  17.033569  34.627949
21 2006-10-01  5.819994  40.624153  ...  16.398823  16.973934  36.740932
22 2006-11-01  5.714560  41.688469  ...  16.402723  16.839388  38.071953
23 2006-12-01  5.278764  41.218037  ...  17.292757  17.947874  36.643532
24 2007-01-01  5.714560  43.059490  ...  18.202139  18.564781  36.680527
25 2007-02-01  5.559920  43.519367  ...  17.988695  18.236647  36.680527
26 2007-03-01  5.545864  45.275547  ...  19.274303  18.490196  34.151123
27 2007-04-01  5.651299  49.051327  ...  18.927237  18.616982  33.994095
28 2007-05-01  5.862169  53.307552  ...  20.392494  21.470690  33.162579
29 2007-06-01  6.621296  53.117615  ...  20.471415  20.306644  31.841948
30 2007-07-01  5.981658  53.456799  ...  19.317125  21.021841  34.117195
31 2007-08-01  5.489631  51.616165  ...  19.839298  20.872541  34.533958
32 2007-09-01  5.967603  53.428234  ...  21.053442  22.068684  36.552395
33 2007-10-01  6.234704  50.825962  ...  20.794699  22.960802  41.693039
34 2007-11-01  5.278764  49.209545  ...  19.175407  21.756039  40.701916
35 2007-12-01  4.730503  49.661259  ...  20.856577  21.997721  39.997463
36 2008-01-01  4.667242  48.586723  ...  19.315918  19.550722  44.526752
37 2008-02-01  4.589923  49.782692  ...  17.649586  18.483343  41.998791
38 2008-03-01  4.020575  53.884804  ...  19.407948  18.549505  37.180870
39 2008-04-01  5.805936  56.355682  ...  19.615709  19.673666  36.358654
40 2008-05-01  4.779706  57.139065  ...  20.428194  19.912649  39.089039
41 2008-06-01  3.380939  51.040749  ...  17.248764  18.323580  42.896797
42 2008-07-01  3.373909  48.067631  ...  15.774250  17.619621  39.526779
43 2008-08-01  3.134925  49.197205  ...  16.581343  18.416971  37.169678
44 2008-09-01  3.655068  41.455593  ...  14.471747  16.828033  31.944490
45 2008-10-01  1.539346  26.570520  ...  13.875669  15.558977  21.759100
46 2008-11-01  1.890795  28.798733  ...  15.037150  17.417389  27.797789
47 2008-12-01  1.609636  31.384228  ...  15.005560  18.084211  33.621693

[48 rows x 21 columns]

In [0]:
#we only keep the data from Dec-30-2004 to Sep-30-2008 (Oct-1-2008) as the sample
df_stock_price_sample_data = df_stock_price_full.iloc[:-2,:].copy()
print (df_stock_price_sample_data.shape)

(46, 21)


In [0]:
#compute the monthly return rate
df_monthly_r = df_stock_price_full.copy()
for row in range(47):
  for col in range(1,21):
    r = (df_monthly_r.iloc[row+1,col]-df_monthly_r.iloc[row,col])/df_monthly_r.iloc[row,col]
    df_monthly_r.iat[row,col] = r

#delete the last row+
df_monthly_r.drop(df_monthly_r.tail(1).index,inplace=True)

df_monthly_r_full_data = df_monthly_r.drop(columns=['Date'])

display(df_monthly_r_full_data)

F       CAT       DIS  ...         T        VZ       NEM
0  -0.032168  0.076198 -0.024101  ...  0.025628  0.021605  0.081991
1  -0.104348 -0.037980  0.028275  ... -0.015378 -0.013067 -0.061111
2  -0.195940 -0.037073 -0.081100  ...  0.004643  0.008451 -0.099300
3   0.107228  0.078873  0.039394  ... -0.004379  0.000869 -0.019226
4   0.026053  0.012751 -0.082361  ...  0.015825 -0.023459  0.050946
5   0.048828  0.131256  0.018268  ...  0.029474 -0.009262 -0.037919
6  -0.063099  0.034149 -0.017550  ... -0.001775 -0.031921  0.054061
7  -0.011033  0.058749 -0.042080  ... -0.004568 -0.000612  0.191764
8  -0.156186 -0.104851  0.009946  ... -0.005007 -0.036097 -0.094672
9  -0.010683  0.103665  0.022979  ...  0.058695  0.029302  0.082629
10 -0.050430 -0.000173 -0.038508  ... -0.016860 -0.058161  0.160283
11  0.111399  0.175351  0.067283  ...  0.059616  0.051129  0.157303
12 -0.060193  0.080579  0.105887  ...  0.077559  0.079808 -0.143690
13 -0.001255 -0.017378 -0.003573  ... -0.019935  0.010682 -0.019463
14 -0.126885  0.054727  0.002510  ... -0.030696 -0.030240  0.126802
15  0.044726 -0.033778  0.090844  ...  0.006632 -0.042582 -0.106409
16 -0.032123  0.020974 -0.016393  ...  0.070223  0.073053  0.014957
17 -0.037518 -0.048470 -0.010333  ...  0.075296  0.009854 -0.030274
18  0.264046 -0.059702 -0.001347  ...  0.050532  0.054478  0.000391
19 -0.033453 -0.008289  0.042496  ...  0.045937  0.055429 -0.165854
20  0.023486 -0.077356  0.017793  ...  0.051904 -0.003501  0.061020
21 -0.018116  0.026199  0.050540  ...  0.000238 -0.007927  0.036227
22 -0.076261 -0.011284  0.036914  ...  0.054261  0.065827 -0.037519
23  0.082556  0.044676  0.035685  ...  0.052587  0.034372  0.001010
24 -0.027061  0.010680 -0.026159  ... -0.011726 -0.017675  0.000000
25 -0.002528  0.040354  0.005255  ...  0.071468  0.013903 -0.068958
26  0.019011  0.083396  0.015974  ... -0.018007  0.006857 -0.004598
27  0.037314  0.086771  0.013151  ...  0.077415  0.153285 -0.024461
28  0.129496 -0.003563 -0.023499  ...  0.003870 -0.054216 -0.039823
29 -0.096603  0.006386 -0.033392  ... -0.056385  0.035220  0.071454
30 -0.082256 -0.034432  0.018182  ...  0.027032 -0.007102  0.012216
31  0.087068  0.035107  0.023512  ...  0.061199  0.057307  0.058448
32  0.044759 -0.048706  0.006979  ... -0.012290  0.040425  0.140638
33 -0.153326 -0.031803 -0.042738  ... -0.077870 -0.052470 -0.023772
34 -0.103862  0.009179 -0.026244  ...  0.087673  0.011109 -0.017308
35 -0.013373 -0.021637 -0.065603  ... -0.073869 -0.111239  0.113239
36 -0.016566  0.024615  0.086126  ... -0.086267 -0.054595 -0.056774
37 -0.124043  0.082400 -0.031780  ...  0.099626  0.003580 -0.114716
38  0.444056  0.045855  0.033461  ...  0.010705  0.060603 -0.022114
39 -0.176755  0.013901  0.036078  ...  0.041420  0.012147  0.075096
40 -0.292647 -0.106728 -0.071428  ... -0.155639 -0.079802  0.097412
41 -0.002079 -0.058250 -0.027244  ... -0.085485 -0.038418 -0.078561
42 -0.070833  0.023500  0.065898  ...  0.051165  0.045254 -0.059633
43  0.165919 -0.157359 -0.051314  ... -0.127227 -0.086276 -0.140577
44 -0.578846 -0.359061 -0.155751  ... -0.041189 -0.075413 -0.318847
45  0.228311  0.083860 -0.130838  ...  0.083706  0.119443  0.277525
46 -0.148699  0.089778  0.007549  ... -0.002101  0.038285  0.209510

[47 rows x 20 columns]

In [0]:
#Get the monthly return of Oct-2008
df_r_Oct_2008 = df_monthly_r_full_data.iloc[[-2]].copy()
#Get the monthly return of Nov-2008
df_r_Nov_2008 = df_monthly_r_full_data.iloc[[-1]].copy()
#Get the monthly return from Jan-2005 to Sep-2008
df_monthly_r_sample = df_monthly_r_full_data.iloc[:-2,:]
df_monthly_r_sample

F       CAT       DIS  ...         T        VZ       NEM
0  -0.032168  0.076198 -0.024101  ...  0.025628  0.021605  0.081991
1  -0.104348 -0.037980  0.028275  ... -0.015378 -0.013067 -0.061111
2  -0.195940 -0.037073 -0.081100  ...  0.004643  0.008451 -0.099300
3   0.107228  0.078873  0.039394  ... -0.004379  0.000869 -0.019226
4   0.026053  0.012751 -0.082361  ...  0.015825 -0.023459  0.050946
5   0.048828  0.131256  0.018268  ...  0.029474 -0.009262 -0.037919
6  -0.063099  0.034149 -0.017550  ... -0.001775 -0.031921  0.054061
7  -0.011033  0.058749 -0.042080  ... -0.004568 -0.000612  0.191764
8  -0.156186 -0.104851  0.009946  ... -0.005007 -0.036097 -0.094672
9  -0.010683  0.103665  0.022979  ...  0.058695  0.029302  0.082629
10 -0.050430 -0.000173 -0.038508  ... -0.016860 -0.058161  0.160283
11  0.111399  0.175351  0.067283  ...  0.059616  0.051129  0.157303
12 -0.060193  0.080579  0.105887  ...  0.077559  0.079808 -0.143690
13 -0.001255 -0.017378 -0.003573  ... -0.019935  0.010682 -0.019463
14 -0.126885  0.054727  0.002510  ... -0.030696 -0.030240  0.126802
15  0.044726 -0.033778  0.090844  ...  0.006632 -0.042582 -0.106409
16 -0.032123  0.020974 -0.016393  ...  0.070223  0.073053  0.014957
17 -0.037518 -0.048470 -0.010333  ...  0.075296  0.009854 -0.030274
18  0.264046 -0.059702 -0.001347  ...  0.050532  0.054478  0.000391
19 -0.033453 -0.008289  0.042496  ...  0.045937  0.055429 -0.165854
20  0.023486 -0.077356  0.017793  ...  0.051904 -0.003501  0.061020
21 -0.018116  0.026199  0.050540  ...  0.000238 -0.007927  0.036227
22 -0.076261 -0.011284  0.036914  ...  0.054261  0.065827 -0.037519
23  0.082556  0.044676  0.035685  ...  0.052587  0.034372  0.001010
24 -0.027061  0.010680 -0.026159  ... -0.011726 -0.017675  0.000000
25 -0.002528  0.040354  0.005255  ...  0.071468  0.013903 -0.068958
26  0.019011  0.083396  0.015974  ... -0.018007  0.006857 -0.004598
27  0.037314  0.086771  0.013151  ...  0.077415  0.153285 -0.024461
28  0.129496 -0.003563 -0.023499  ...  0.003870 -0.054216 -0.039823
29 -0.096603  0.006386 -0.033392  ... -0.056385  0.035220  0.071454
30 -0.082256 -0.034432  0.018182  ...  0.027032 -0.007102  0.012216
31  0.087068  0.035107  0.023512  ...  0.061199  0.057307  0.058448
32  0.044759 -0.048706  0.006979  ... -0.012290  0.040425  0.140638
33 -0.153326 -0.031803 -0.042738  ... -0.077870 -0.052470 -0.023772
34 -0.103862  0.009179 -0.026244  ...  0.087673  0.011109 -0.017308
35 -0.013373 -0.021637 -0.065603  ... -0.073869 -0.111239  0.113239
36 -0.016566  0.024615  0.086126  ... -0.086267 -0.054595 -0.056774
37 -0.124043  0.082400 -0.031780  ...  0.099626  0.003580 -0.114716
38  0.444056  0.045855  0.033461  ...  0.010705  0.060603 -0.022114
39 -0.176755  0.013901  0.036078  ...  0.041420  0.012147  0.075096
40 -0.292647 -0.106728 -0.071428  ... -0.155639 -0.079802  0.097412
41 -0.002079 -0.058250 -0.027244  ... -0.085485 -0.038418 -0.078561
42 -0.070833  0.023500  0.065898  ...  0.051165  0.045254 -0.059633
43  0.165919 -0.157359 -0.051314  ... -0.127227 -0.086276 -0.140577
44 -0.578846 -0.359061 -0.155751  ... -0.041189 -0.075413 -0.318847

[45 rows x 20 columns]

## 2.0 Parameter Estimation

### 2.1 Estimate the sample mean

In [0]:
#compute the sample mean for each stock (n=45)
r_sample_means = df_monthly_r_sample.mean(axis = 0) 
display(r_sample_means)

F      -0.024767
CAT     0.002276
DIS     0.000021
MCD     0.016395
KO      0.006798
PEP     0.004174
WMT     0.003744
C      -0.023051
WFC     0.009118
JPM     0.007839
AAPL    0.031563
IBM     0.003081
PFE    -0.001950
JNJ     0.001406
XOM     0.011410
MRO     0.019815
ED      0.004677
T       0.008135
VZ      0.002234
NEM    -0.004393
dtype: float64

### 2.2 Compute the sample variance

In [0]:
#sample variance for each stock
r_sample_std = df_monthly_r_sample.std(axis = 0, ddof=1)
r_sample_var = r_sample_std**2
display(r_sample_var) 

F       0.021957
CAT     0.007196
DIS     0.002523
MCD     0.002818
KO      0.002031
PEP     0.002249
WMT     0.002129
C       0.008495
WFC     0.005702
JPM     0.005632
AAPL    0.016221
IBM     0.004144
PFE     0.002892
JNJ     0.001277
XOM     0.003762
MRO     0.011952
ED      0.001452
T       0.003348
VZ      0.002610
NEM     0.009671
dtype: float64

### 2.3 Compute the sample covariance

In [0]:
#compute sample covariances
r_sample_cov = np.cov(df_monthly_r_sample.T)

display(r_sample_cov)

array([[ 2.19571849e-02,  5.98011908e-03,  3.26562149e-03,
         3.19291322e-03,  2.75749820e-03,  2.27921991e-03,
         2.74777161e-03,  8.78443030e-03,  3.15327152e-03,
         4.94759276e-03,  2.88076734e-03,  4.67733099e-03,
         1.58508508e-03,  1.85570584e-03,  2.94001642e-03,
         4.39637320e-03,  1.00835062e-03,  1.64008719e-03,
         2.44857244e-03,  3.68185030e-03],
       [ 5.98011908e-03,  7.19551082e-03,  2.32417253e-03,
         1.83091738e-03,  1.78325199e-03,  1.65086433e-03,
         3.79189396e-04,  2.92681749e-03, -2.40942317e-04,
         6.39006455e-04,  4.75301202e-03,  2.54405801e-03,
         1.19077051e-03,  6.81283528e-04,  2.19196643e-03,
         5.22967383e-03, -6.42331534e-05,  2.22480224e-03,
         2.10347191e-03,  3.90776114e-03],
       [ 3.26562149e-03,  2.32417253e-03,  2.52276056e-03,
         1.11835215e-03,  1.10032479e-03,  1.05358013e-03,
         4.31567342e-04,  1.61271023e-03, -2.69939317e-04,
         1.74696983e-04,  1.5

In [0]:
r_sample_cov.shape

(20, 20)

## 2.3 Compute the market portfolio (P4)

### 2.3.1 Get the shares outstanding of each stock as of September 2008

In [0]:
#Compute estimated market portfolio

#Searched shares outstandingg of the 20 stocks as of Sepetember 2008:

shares_outstanding = {
    'F':2.279,
    'CAT':0.625,
    'DIS':1.948,
    'MCD':1.136,
    'KO':4.658,
    'PEP':1.593,
    'WMT':3.958,
    'C':0.583,
    'WFC':3.331,
    'JPM':3.445,
    'AAPL':6.315,
    'IBM':1.384,
    'PFE':6.736,
    'JNJ':2.831,
    'XOM':5.178,
    'MRO':0.711,
    'ED':0.274,
    'T':5.893,
    'VZ':2.845,
    'NEM':0.455
}

In [0]:
pd_shares_outstanding = pd.Series(shares_outstanding)
display(pd_shares_outstanding)

F       2.279
CAT     0.625
DIS     1.948
MCD     1.136
KO      4.658
PEP     1.593
WMT     3.958
C       0.583
WFC     3.331
JPM     3.445
AAPL    6.315
IBM     1.384
PFE     6.736
JNJ     2.831
XOM     5.178
MRO     0.711
ED      0.274
T       5.893
VZ      2.845
NEM     0.455
dtype: float64

### 2.3.2 Compute the market capitalization

In [0]:
market_capital = df_stock_price_full.iloc[-3,1:]*pd_shares_outstanding
market_capital


F       3.50817
CAT     16.6066
DIS     42.8201
MCD     45.7619
KO      63.7062
PEP     64.0448
WMT     166.495
C       72.0842
WFC     81.8628
JPM     106.498
AAPL    84.0259
IBM     89.7189
PFE     75.4601
JNJ     121.656
XOM     261.075
MRO     9.05964
ED      7.21156
T       81.7693
VZ      44.2653
NEM     9.90039
dtype: object

### 2.3.3 Compute Market portfolio (Assume the 20 stocks are the all market size)

In [0]:
total_mrkt = market_capital.sum()
x_p4_mrkt = market_capital/total_mrkt
x_p4_mrkt

F       0.00242356
CAT      0.0114724
DIS      0.0295815
MCD      0.0316138
KO       0.0440103
PEP      0.0442442
WMT        0.11502
C        0.0497981
WFC      0.0565534
JPM       0.073572
AAPL     0.0580478
IBM      0.0619807
PFE      0.0521303
JNJ      0.0840438
XOM       0.180359
MRO     0.00625869
ED      0.00498198
T        0.0564889
VZ       0.0305799
NEM     0.00683951
dtype: object

## 2.4 Compute the performance of market portfolio (P4) in October 2008

### 2.4.1 Compute the realized portfolio return of market portfolio (P4) in October 2008

In [0]:
#calculate P market realized return rate in Oct 2008

r_oct_p4_mrkt = float(np.dot(df_r_Oct_2008,x_p4_mrkt))
r_oct_p4_mrkt

-0.0431447155993136

### 2.4.2 Compute the realized portfolio variance and standard deviation of market portfolio (P4) in October 2008

In [0]:
r_sample_cov_till_Oct = np.cov(df_monthly_r_full_data.iloc[:-1,:].T)

In [0]:
var_oct_p4_mrkt = np.dot(np.dot(x_p4_mrkt.T,r_sample_cov_till_Oct),x_p4_mrkt)
var_oct_p4_mrkt

0.0011814047238156858

In [0]:
std_oct_p4_mrkt = np.sqrt(var_oct_p4_mrkt)
std_oct_p4_mrkt

0.03437156853877469

### 2.4.3 Compute the realized portfolio sharp ratio of market portfolio (P4) in October 2008

#### 2.4.3.1 risk free rate
https://www.macrotrends.net/2016/10-year-treasury-bond-rate-yield-chart


In [0]:
rf_month = np.power(1+0.036,1/12)-1
rf_month

0.0029516094330215292

In [0]:
sharp_oct_p4_mrkt = float((r_oct_p4_mrkt-rf_month)/std_oct_p4_mrkt)
sharp_oct_p4_mrkt

-1.3411178771295729

## 2.5 Compute the portfolio based on MVO (P1)

### 2.5.1 compute λ

In [0]:
#calculate market expected return rate
r_exp_mrkt = np.dot(x_p4_mrkt,r_sample_means)
r_exp_mrkt

0.0060865585680787435

In [0]:
#calculate market expected variance
x_mrkt = np.array(x_p4_mrkt).reshape(20,1)
var_exp_mrkt = float(np.dot(np.dot(x_mrkt.T,r_sample_cov),x_mrkt))
var_exp_mrkt

0.0011543678123873253

In [0]:
#Risk aversion coefficient lambda
λ = (r_exp_mrkt-rf_month)/var_exp_mrkt
λ

2.715728125313792

###2.5.2 compute x of Portfolio 1

https://pypi.org/project/qpsolvers/


https://scaron.info/blog/quadratic-programming-in-python.html


In [0]:
r_sample_means

F      -0.024767
CAT     0.002276
DIS     0.000021
MCD     0.016395
KO      0.006798
PEP     0.004174
WMT     0.003744
C      -0.023051
WFC     0.009118
JPM     0.007839
AAPL    0.031563
IBM     0.003081
PFE    -0.001950
JNJ     0.001406
XOM     0.011410
MRO     0.019815
ED      0.004677
T       0.008135
VZ      0.002234
NEM    -0.004393
dtype: float64

In [0]:
f = -1*np.array(r_sample_means)
print(f.shape)
print(f)

(20,)
[ 2.47672181e-02 -2.27597375e-03 -2.06740796e-05 -1.63954823e-02
 -6.79777556e-03 -4.17430824e-03 -3.74375358e-03  2.30509605e-02
 -9.11769936e-03 -7.83930154e-03 -3.15632374e-02 -3.08112933e-03
  1.94988622e-03 -1.40590012e-03 -1.14095467e-02 -1.98145068e-02
 -4.67715734e-03 -8.13488780e-03 -2.23365579e-03  4.39310731e-03]


In [0]:
A = np.zeros(20)
print(A.shape)
print(A)

(20,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
b = 0.
print(b)

0.0


In [0]:
Aeq = np.ones(20)
print(Aeq.shape)
print(Aeq)

(20,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [0]:
beq = np.array([1.])
print(beq.shape)
print(beq)

(1,)
[1.]


In [0]:
Q = 2*λ*r_sample_cov
print(Q.shape)

(20, 20)


In [0]:
np.all(np.linalg.eigvals(Q) > 0)

True

In [0]:
from numpy import array, dot
from qpsolvers import solve_qp
x_p1_mvo = solve_qp(Q, f, A, b, Aeq, beq, solver='quadprog')
print ("QP solution or x_mvo:", x_p_MVO)

QP solution or x_mvo: [ 0.07942287 -0.23390853  1.08976222  1.24489521 -0.08250134  0.41608393
 -0.25600045 -2.4240574   3.0797168   0.54151626  0.41419343 -1.64107293
 -2.33264349 -0.01777243  0.82519546  0.82983423 -1.32067097  1.03393147
 -0.27827866  0.03235432]


In [0]:
r_exp_p1_MVO = np.dot(r_sample_means,x_p1_mvo)
r_exp_p1_MVO

0.14622166969587586

### 2.5.3 Compute the realized portfolio return of MVO portfolio (P1) in October 2008

In [0]:
r_oct_p1_MVO = float(np.dot(df_r_Oct_2008,x_p_MVO))
r_oct_p1_MVO

0.6744859763019845

### 2.5.4 Compute the realized portfolio variance and standard deviation of MVO portfolio (P1) in October 2008

In [0]:
var_oct_p1_mvo = np.dot(np.dot(x_p1_mvo.T,r_sample_cov_till_Oct),x_p1_mvo)
var_oct_p1_mvo

0.031622592547295866

In [0]:
std_oct_p1_mvo = np.sqrt(var_oct_p1_mvo)
std_oct_p1_mvo

0.1778274234961972

### 2.5.5 Compute the realized portfolio sharp ratio of MVO portfolio (P1) in October 2008

In [0]:
sharp_oct_p1_mvo = float((r_oct_p1_MVO-rf_month)/std_oct_p1_mvo)
sharp_oct_p1_mvo

3.7763262474717436

## 2.6 Compute the portfolio based on Robust MVO (P2)

### 2.6.1 Robust MVO with confinence level 0f 90% (P2_90)

In [0]:
chi_90 = 28.41

In [0]:
T = 45 #as we have 45 sample observations
theta = np.diag(np.diag(r_sample_cov))/T
sqrt_theta = np.sqrt(theta)

In [0]:
def opt_func(x,ep):
  return λ*np.dot(np.dot(x.T,r_sample_cov),x)-np.dot(r_sample_means,x)+ep*np.linalg.norm(np.dot(sqrt_theta,x))

In [0]:
from scipy.optimize import LinearConstraint

#define the constraint of e*x = 1
linear_constraint = LinearConstraint([np.ones(20)],[1],[1])

In [0]:
#initial x
x0 = np.array([1/20]*20)
x0

array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
       0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])

In [0]:
from scipy.optimize import minimize

x_p2_RMVO = minimize(lambda x:opt_func(x,chi_90),x0,method='trust-constr',constraints=linear_constraint)

x_p2_RMVO

         cg_niter: 80
     cg_stop_cond: 4
           constr: [array([1.])]
      constr_nfev: [0]
      constr_nhev: [0]
      constr_njev: [0]
   constr_penalty: 1.0
 constr_violation: 0.0
   execution_time: 0.16249585151672363
              fun: 0.05192676433679508
             grad: array([0.05422563, 0.05422562, 0.05422563, 0.05422562, 0.05422563,
       0.05422562, 0.05422562, 0.05422563, 0.05422563, 0.05422562,
       0.05422563, 0.05422562, 0.05422562, 0.05422563, 0.05422562,
       0.05422562, 0.05422563, 0.05422563, 0.05422563, 0.05422563])
              jac: [array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])]
  lagrangian_grad: array([ 1.51339920e-09, -1.74622981e-09,  1.51339920e-09, -8.14907239e-10,
        3.84170563e-09, -1.28056853e-09, -2.21189110e-09,  1.04773791e-09,
        3.37604435e-09, -2.67755239e-09,  1.51339920e-09, -1.28056853e-09,
       -1.28056853e-09,  1.16415336e-10, -8.14907239e-10, -7.79982655e-09,
     

In [0]:
optx = x_p2_RMVO.x
optx

array([0.00207529, 0.0204243 , 0.06022695, 0.06977498, 0.08358788,
       0.07237071, 0.08106483, 0.00770503, 0.03203958, 0.03042164,
       0.01417538, 0.03774146, 0.05162568, 0.1241721 , 0.04978021,
       0.01699058, 0.11874368, 0.05221247, 0.06015992, 0.01470731])

In [0]:
optx.sum()

1.0

In [0]:
r_exp_p2_RMVO = np.dot(r_sample_means,optx)
r_exp_p2_RMVO

0.005259262188784121

In [0]:
r_oct_p2_RMVO = float(np.dot(df_r_Oct_2008,optx))
r_oct_p2_RMVO

-0.02038251400428203

# For test only of using Scipy.minimize to solve MVO

In [0]:
def opt_func_mvo(x):
  return -np.dot(r_sample_means,x)+λ*np.dot(np.dot(x.T,r_sample_cov),x)

In [0]:
#define the constraint of e*x = 1
linear_constraint_mvo = LinearConstraint([np.ones(20)],[1],[1])

In [0]:
opt_MVO_solution = minimize(lambda x:opt_func_mvo(x),x0,method='trust-constr',constraints=linear_constraint_mvo)

In [0]:
x_opt_mvo= opt_MVO_solution.x
x_opt_mvo

array([ 0.07942278, -0.23390866,  1.08976341,  1.24489494, -0.08250207,
        0.41608349, -0.25600095, -2.42405773,  3.07971685,  0.54151714,
        0.41419332, -1.64107312, -2.33264393, -0.0177719 ,  0.82519612,
        0.82983428, -1.32067124,  1.03393169, -0.27827879,  0.03235438])

In [0]:
r_opt_mvo = np.dot(r_sample_means,x_opt_mvo)
r_opt_mvo

0.14622167933283883

In [0]:
r_opt_oct_mvo = float(np.dot(df_r_Oct_2008,x_opt_mvo))
r_opt_oct_mvo

0.6744857913293575

### 2.6.2 Robust MVO with confinence level 0f 95% (P2_95)

In [0]:
chi_95 = 31.41